name: Bug Report / Сообщение об ошибке
description: File a bug report / Сообщить об ошибке в программе

body:
  - type: markdown
    attributes:
      value: |
        **USE THIS FORM ONLY FOR BUGS**
        Voice-over-translation does not guarantee to work with every video or at all. If Voice-over-translation can't translate some media, this is most likely not a software bug, and you should not report it here.
        Please only report software bugs, such as:
          * menu issues
          * feature issus
          * other problems (not feature request)
        Please make sure to check other opened and closed issues, it could be your bug has been reported already.

        **ИСПОЛЬЗУЙТЕ ЭТУ ФОРМУ ТОЛЬКО ДЛЯ БАГОВ**
        Voice-over-translation не гарантирует ни 100% работу с каждым видео, ни работу вообще. Если Voice-over-translation не переводит некоторые медиа, вероятнее всего, это не программная ошибка, и не стоит о ней сообщать здесь.
        Пожалуйста, сообщайте только об программных ошибках, таких как:
          * проблемы с меню
          * проблемы с функциями
          * другие ошибки/проблемы (не запрос функции)
        Также посмотрите другие открытые и закрытые issues. Возможно, ошибка уже обсуждалась или исправлена.
  - type: input
    id: os
    attributes:
      label: Operating system / Операционная система
      description: Enter your OS version. For Windows 10 and 11 include build/update number / Укажите версию вашей ОС. Для Windows 10 и 11 укажите номер сборки/обновления.
      placeholder: ex. Windows 10 20H2
    validations:
      required: false
  - type: dropdown
    id: browser
    attributes:
      label: Browser / Браузер
      description: Select your browser / Выберите ваш браузер
      options:
        - Chrome
        - Firefox
        - Edge
        - Opera
        - Safari
        - Other / Другой
    validations:
      required: true
  - type: dropdown
    id: userscript-manager
    attributes:
      label: Userscript manager / Скриптовый движок
      description: Select the userscript manager you use / Выберите менеджер юзерскриптов, который вы используете
      options:
        - Tampermonkey
        - Violentmonkey
        - Greasemonkey
        - OrangeMonkey
        - AdGuard
        - FireMonkey
        - UserScripts
        - Other / Другой
    validations:
      required: true
  - type: input
    id: script-version
    attributes:
      label: Script version / Версия скрипта
      description: Enter the version of the voice-over-translation script / Введите версию скрипта voice-over-translation
      placeholder: ex. 1.5.3
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug / Опишите ошибку
      description: A clear and concise description of what the bug is / Подробно опишите, в чём заключается ошибка
      placeholder: Attach the screenshots for clarity / При необходимости приложите скриншоты
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information / Дополнительная информация
      description: If you have a hints on why this bug happens, you can express it here / Если у вас есть предположения об источнике бага, вы можете изложить их здесь
