name:  Feature request / Предложить новую функциональность
description:  Suggest an idea or function for this project / Предложить новую идею или функциональность в скрипте

body:
  - type: markdown
    attributes:
      value: |
        If you think of a great function which is missing from the script, go ahead and suggest it here.
        Если вы придумали новую функцию, которой еще нет в скрипте, напишите о ней подробнее здесь.
  - type: textarea
    id: description
    attributes:
      label: Describe your feature / Опишите ваше предложение
    validations:
      required: true
