name: Build

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: ["*"]
  workflow_call:

permissions:
  contents: write

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.18.x, 22.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }} 🛎️
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install 🔧
        shell: bash
        run: npm install
      - name: Build 🔧
        run: npm run build
      - name: Upload Artifact 🚀
        uses: actions/upload-artifact@v4
        with:
          name: vot-${{ matrix.node-version }}
          path: dist/vot*.user.js

  bun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Setup Bun.sh 🛎️
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install 🔧
        shell: bash
        run: bun install
      - name: Build 🔧
        run: bun run build
      - name: Upload Artifact 🚀
        uses: actions/upload-artifact@v4
        with:
          name: vot-bun
          path: dist/vot*.user.js
